### ISSUE TITLE
Didn't worked at all :(

### ISSUE THREAD

**Issue by afrasiyabhaider** [kalynrobinson/flarum-laravel-integration#1]
I've implemented everything as mentioned but it didnt worked. Its not listening events

**Comment by sanushen** [comment]
> I've implemented everything as mentioned but it didnt worked. Its not listening events

It works for me. Did you check your logs?

**Comment by Quirinus** [comment]
> > I've implemented everything as mentioned but it didnt worked. Its not listening events
> 
> It works for me. Did you check your logs?

Thanks for confirming it works. I was thinking about using Flarum with Laravel, but wasn't sure if these instructions were still valid.

**Comment by afrasiyabhaider** [comment]
Working fine

**Comment by anwesha-mohanty** [comment]
I'm stuck at the step where we've to Setup Event Subscriber. Could you tell me where(in which folder,or path) the event subscriber is to be created?

**Comment by KenzoKai** [comment]
`php artisan make:listener FlarumEventSubscriber`

**Comment by KenzoKai** [comment]
> 
> 
> I'm stuck at the step where we've to Setup Event Subscriber. Could you tell me where(in which folder,or path) the event subscriber is to be created?

`php artisan make:listener FlarumEventSubscriber`

Also add the following to your EventServiceProvider

```
    /**
     * The subscriber classes to register.
     *
     * @var array
     */
    protected $subscribe = [
        FlarumEventSubscriber::class
    ];
```

It may also help to update the subscribe function

```    
public function subscribe($events)
    {
        Event::listen(
            Registered::class,
            'App\Listeners\FlarumEventSubscriber@onUserRegistration'
        );

        Event::listen(
            Login::class,
            'App\Listeners\FlarumEventSubscriber@onUserLogin'

        );

        Event::listen(
            Logout::class,
            'App\Listeners\FlarumEventSubscriber@onUserLogout'
        );
    }
```
